sudo: false
language: ruby
rvm:
- 2.6.0
before_install: gem install bundler -v 1.13.7
deploy:
  provider: rubygems
  api_key:
    secure: D4y+7QnSujAUqGX4V+9yEQcLKa6GF+24c4eDFhQi0RrVQb5eGnxHAUoRMypTwNXWwO3s0JucatfblYFaSkzpCAlqDyFbNP7py0SpH7rnC/l6FiAihckDsZd/tG1bu+Bv1yr2DTyLHVI2MlaRYVrdLZaG9N+YUrDRBOgl1h3iPP+13gOBOxmdAaCycHPcqqczvX3jdWqsVimzkzOTZzfYheyoWnhviqiTMA2yDgV9g1Vf5I8O3y/02Fb02ROWrurhKFRgn3PzZ9xQQXFSSCsVZ13FgVv++IHLskNwXhb3jLHwNq0+p+jKZhNcSQ5Ll1tOuVnODbUBFWuSBe62Z+96wBCMwauCs0pMuOXVxsrhggITF0hLPxEQfyrZ8n2gnE9Tw4CKavF+s4SQZTWKCcHlGZuOmRHnkHAGL8Q1af4CcQ4EO2lR9bsThNVrbOk1WV7ovP1KCO1UoCybP0dDsv8mT4WCyuFenabNkWPPf/RD/S+I3+CdNq2zss7u2os0/iWR7Ec0lHVx6LFW7dQ/hXinGln25cwpMo/iigeY3a6O9WxQvmS0kxBuZ007gayVtW7SWDDiIMs305dtFeTNfo7GsJ+K5whx9GWq0bhziXv0mg3I76JILT6g8en1uZKF64Z853Oy05OAWBDlZI6HZwbKA18Sz1KHqRSX3vHQy7Qj8go=
  gem: mumukit-login
  on:
    tags: true
    repo: mumuki/mumukit-login
